name: Notify Bluesky of New Articles

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Get Bluesky Message
        id: get_message
        env:
          DEVTO_USER: ${{ vars.DEVTO_USER }}
          LAST_ARTICLE_ID: ${{ vars.LAST_BLUESKY_ARTICLE_ID }}
        run: bun run scripts/bluesky_devto_notifier.js

      - name: Post to Bluesky
        if: steps.get_message.outputs.bluesky_message != ''
        uses: myConsciousness/bluesky-post@v5
        with:
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          text: ${{ steps.get_message.outputs.bluesky_message }}

      - name: Update last processed article ID
        if: steps.get_message.outputs.new_article_id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.setRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'LAST_BLUESKY_ARTICLE_ID',
              value: '${{ steps.get_message.outputs.new_article_id }}'
            })
