name: Notify Discord of New Articles (RSS)

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install feedparser requests

      - name: Run Discord RSS Notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RSS_FEED_URL: "https://dev.to/feed/jonashdown"
        run: python scripts/discord_rss_notifier.py