name: Proofread PRs
on: [pull_request]

jobs:
  test:
    permissions: write-all # Required since GitHub now gives actions read-only permissions by default
    runs-on: ubuntu-latest
    name: Proofread PRs
    steps:
      - name: Proofread PR
        uses: streetsidesoftware/cspell-action@v6.11.0
        id: proofread
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required to write a PR review