name: check_status
on: 
    workflow_run:
      workflows: [publish]

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
    check_status:
      runs-on: ubuntu-latest
      steps:
        - name: Check Published Status
          run: |
            gh auth login
            "[ 'success' = '$(gh run list -b main -w publish | awk 'NR==1{print $2}')' ]"

