name: check_status
on: 
    workflow_run:
      workflows: [publish]

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
    check_status:
      runs-on: ubuntu-latest
      steps:
        - name: Check Published Status
          run: |
            [ "success" == "$(gh run list -b main -w publish -R jonashdown/Blog | awk 'NR==1{print $2}')" ]

